'use client';

import React, { useState, useEffect } from 'react';
// import type { Metadata } from "next"; // Metadata import might need adjustment for client component
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Correct path for global styles

// Import dummy components
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';
import SidebarToggleButton from '../components/SidebarToggleButton';

// Metadata export might need to be in a separate server component or not used in client component
// For now, I'll keep it commented out or modify it if it causes issues.
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true); // Default to true for desktop

  const toggleSidebar = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  useEffect(() => {
    const handleResize = () => {
      // Collapse sidebar by default on smaller screens
      if (window.innerWidth < 768) {
        setIsSidebarOpen(false);
      } else {
        setIsSidebarOpen(true); // Show sidebar by default on larger screens
      }
    };

    window.addEventListener('resize', handleResize);
    handleResize(); // Call once on mount

    return () => window.removeEventListener('resize', handleResize);
  }, []);

  return (
    <html lang="en">
      <head>
        <title>LogeekMind</title>
        <meta name="description" content="Your all-in-one AI-powered learning assistant." />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#6a11cb" />
        <link rel="apple-touch-icon" href="/icon-192.png"></link>
        <meta name="apple-mobile-web-app-status-bar" content="#6a11cb" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={`main-layout-container ${!isSidebarOpen ? 'sidebar-closed' : ''}`}>
          <Navbar />
          <div className="content-area-container">
            <Sidebar isOpen={isSidebarOpen} onClose={toggleSidebar} />
            {isSidebarOpen && typeof window !== 'undefined' && window.innerWidth < 768 && <div className="mobile-backdrop" onClick={toggleSidebar}></div>}
            <SidebarToggleButton toggleSidebar={toggleSidebar} isSidebarOpen={isSidebarOpen} />
            <main className="main-content-area">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}